spring:
  main:
    web-application-type: none
magus:
  host: 192.168.1.21
  port: 6644
  user: admin
  passwd: admin
  maxconn: 10
  timeout: 10000
points: point1,point2
interval: 60000
push-url: http://localhost:6666/gas/batch/add
